sudo: required
services:
  - docker
language: generic
install: true
branches:
  only:
    - master
before_install:
  - sudo docker build -t srp33/shinylearner_environment .
  - sudo docker images
after_success:
  - sudo docker login -e="$DOCKER_MAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"; docker push srp33/shinylearner_environment:version1;
