sudo: required
services:
  - docker
language: generic
install: true
branches:
  only:
    - master
script:
  - sudo docker build -t srp33/shinylearner_environment:version1 .
  - sudo docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - sudo docker push srp33/shinylearner_environment:version1
