sudo: required
services:
  - docker
language: generic
install: true
branches:
  only:
    - master
#before_install:
#after_success:
script:
  - sudo docker build -t srp33/shinylearner_environment .
  - sudo docker images
  - sudo docker login -e="$DOCKER_MAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - sudo docker push srp33/shinylearner_environment
